name: firehose_cli
description: CLI tool for reading/writing Firestore with JSON I/O
version: 0.2.0
homepage: https://github.com/WAMF/firehose_cli
repository: https://github.com/WAMF/firehose_cli

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.6.0
  dotenv: ^4.2.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  kiss_firebase_repository_rest: ^0.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

executables:
  firehose:
